Demolish = "Left Ctrl"
Console_cheat = "Right Alt"
Rotate_building = "R"
Build = "LMB"
Move_up = "W"
Pipette = "Q"
Control_unit = "V"
Shoot = "LMB"
Move_left = "A"
Move_down = "S"
Move_right = "D"
Pause = "Space"
Hide_GUI = "F1"
Screenshot = "F2"
Show_FPS = "F3"
Show_atlas = "F4"
Fullscreen = "F11"
