name: Turret_2_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest] # chacge ubuntu version to latest, when letest would be 24.04+ 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: >
          cmake -S . -B build 
          -DCMAKE_BUILD_TYPE=Debug
          ${{ runner.os == 'Linux' && '-DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_C_COMPILER=gcc-14' || '' }}
          #toggle later -DCMAKE_CXX_FLAGS="${{ runner.os == 'Windows' && '/W3 /WX' || '-Wall -Werror' }}"
          -DCMAKE_CXX_FLAGS="${{ runner.os == 'Windows' && '/W3' || '-Wall' }}"

      - name: Build
        run: cmake --build build --config Debug
